update release script

diff --git a/release b/release
--- a/release
+++ b/release
@@ -6,21 +6,23 @@ die () {
     exit 1
 }
 
-usage="Usage: release <version>"
-
-if [[ `git status --porcelain` ]]; then
+if [[ -n $(git status --porcelain) ]]; then
   die "dirty workspace"
 fi
 
 VERSION="$1"
 
 if [[ -z "$VERSION" ]]; then
-  die "$usage"
+  die "Usage: release <version>"
 fi
 
-git pull origin $(git rev-parse --abbrev-ref HEAD)
-./gradlew clean build
-./gradlew -Pversion=${VERSION} publish
+if ! git pull origin $(git rev-parse --abbrev-ref HEAD); then
+  die "pull failed"
+fi
+
+if ! ./gradlew clean -Pversion=${VERSION} clean test publish; then
+  die "build failed"
+fi
 
 read -e -p "Upload successful. Also tag? [y/N]"
 if [[ "$REPLY" == [Yy]* ]]; then
